local monitor = peripheral.wrap("left")
monitor.setTextScale(2)
monitor.write("Gerrits Te doen lijst:")
monitor.setCursorPos(4,3)
monitor.setTextScale(2)
monitor.write("1 Auto Farm")
monitor.setCursorPos(4,4)
monitor.setTextScale(2)
monitor.write("2 Opslag")
